### ISSUE TITLE
About the Exchange rates

### ISSUE THREAD

**Issue by syuukawa** [CoinAlpha/hummingbot_chinese#6]
It is a little confused about the stablecoins Exchange rates ,

Can you provide a simple example of the impact of exchange rates on earnings

Thans

**Comment by moraliang** [comment]
If you do cross-exchange market making or arbitrage by using different stablecoins at different exchanges, say on one side, you use WETH-DAI and on the other you use ETH-USDC, you'll need to have a relatively accurate exchange rate between DAI and USDC. Basically the exchange rate is only needed in these scenarios.

**Comment by xiandong79** [comment]
@syuukawa Hi, do we have a wechat group? My wechat id is: qi839395901
